# Copyright 2019 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
data:
  policy.rego: |
    package knative.dev

    default allow = false

    allow {
      endswith(input.source.identity, ":eventing-broker-ingress")
    }
kind: ConfigMap
metadata:
  name: imc-dispatcher-policy
  namespace: knative-eventing
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: imc-dispatcher
  namespace: knative-eventing
  labels:
    eventing.knative.dev/release: devel
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      messaging.knative.dev/channel: in-memory-channel
      messaging.knative.dev/role: dispatcher
  template:
    metadata:
      labels: *labels
      annotations:
        proxy.knative.dev/inject: "true"
        proxy.knative.dev/settings: "{\"tokenExpiration\":7200,\"audiences\":[\"svc.cluster.local\"],\"policy\":\"imc-dispatcher-policy\",\"servicePort\":8080}"
    spec:
      serviceAccountName: imc-dispatcher
      containers:
      - name: dispatcher
        image: knative.dev/eventing/cmd/in_memory/channel_dispatcher
        env:
          - name: CONFIG_LOGGING_NAME
            value: config-logging
          - name: CONFIG_OBSERVABILITY_NAME
            value: config-observability
          - name: METRICS_DOMAIN
            value: knative.dev/inmemorychannel-dispatcher
          - name: SYSTEM_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
          - containerPort: 9090
            name: metrics
        volumeMounts:
          - name: config-logging
            mountPath: /etc/config-logging
        resources:
          # Set resource requests and limits based on the benchmarking results in
          # https://github.com/knative/eventing/issues/2311#issuecomment-565311345
          requests:
            cpu: 1000m
            memory: 150Mi
          limits:
            cpu: 2200m
            memory: 300Mi
      volumes:
        - name: config-logging
          configMap:
            name: config-logging
